---
- hosts: localhost
  connection: local
  become: false
  
  roles:
    - role: git
      tags:
      - git

    - role: gpg
      tags:
      - gpg

    - role: ssh
      tags:
      - ssh

    - role: zsh
      tags:
      - zsh
