---
- name: ~/.ssh
  file:
    path: /home/cees/.ssh
    state: directory
    mode: 0700

- name: ~/.ssh/id_ed25519
  copy:
    src: id_ed25519
    dest: ~/.ssh/id_ed25519
    mode: 0600
  
- name: ~/.ssh/id_ed25519.pub
  copy:
    src: id_ed25519.pub
    dest: ~/.ssh/id_ed25519.pub
    mode: 0644
