---
- name: ~/.config/nvim
  file:
    path: ~/.config/nvim
    state: directory
    mode: 0700

- name: init.vim
  template:
    src: init.vim.j2
    dest: ~/.config/nvim/init.vin
    mode: 0644
